name: Docs Governance
on:
  pull_request:
    paths:
      - '**/*.md'
      - 'scripts/**'
      - 'docs/**'
      - 'src/**'
      - 'server/**'
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci || npm install
      - name: Breadcrumb Validation
        run: npm run docs:validate
      - name: Drift Check
        run: npm run docs:drift
      - name: Link Check
        run: npm run docs:links
      - name: Generate Context (non-blocking)
        run: npm run docs:context
      - name: Governance Summary
        run: npm run docs:gov
      - name: Archive Doc Graph
        uses: actions/upload-artifact@v4
        with:
          name: doc-graph
          path: docs/doc-graph.json
